require '../scripts/rakefuns.rb'
require '../scripts/rakeconsts.rb'

Final = Src.ext('.e')

task :default => Final

file Depend do
	makedep Src, Depend
end

import Depend

rule '.e' => '.o' do |rule|
	invoke Compilers[:ld], rule.source, rule.name
end

task :clean do
	sh "#{Rm} #{Obj}"
	sh "#{Rm} #{Depend}"
end

task :distclean => :clean do
	sh "#{Rm} #{Final}"
end
