Basedir = '../..'

require "#{Basedir}/scripts/starforge"

Incldir = "#{Basedir}/include/starlia"
Builddir = "#{Basedir}/build"

Compilers[:cpp][1] << "I #{Incldir}"

Final = "#{Builddir}/libstarlia.a"

task :default => Final

sh "#{Rm} #{Depend}"

file Depend do
	puts "Generating #{Depend}"
	makedep Src, Embassy, Depend
end

import Depend

concfile Final => Obj do
	invoke Compilers[:ar], Obj, Final, ''
end

task :clean do
	sh "#{Rm} #{Obj}"
	sh "#{Rm} #{Depend}"
	sh "#{Rm} #{Embassy.ext('cpp')} #{Embassy.ext('h')}"
end

task :find do
	puts "Src: #{Src.inspect}"
	puts "Mby: #{Embassy.inspect}"
	puts "Obj: #{Obj.inspect}"
end

task :distclean => :clean do
	sh "#{Rm} #{Final}"
end
