Basedir = '../..'

require "#{Basedir}/scripts/rakefuns.rb"
require "#{Basedir}/scripts/rakeconsts.rb"

Incldir = "#{Basedir}/include/starlia"
Builddir = "#{Basedir}/build"

Compilers[:cpp][1] << "I #{Incldir}"

Final = "#{Builddir}/libstarlia.a"

task :default => Final

sh "#{Rm} #{Depend}"

file Depend do
	puts "Generating #{Depend}"
	makedep Src, Depend
end

import Depend

concfile Final => Obj do
	invoke Compilers[:ar], Obj, Final, ''
end

task :clean do
	sh "#{Rm} #{Obj}"
	sh "#{Rm} #{Depend}"
end

task :distclean => :clean do
	sh "#{Rm} #{Final}"
end
